version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/birdnet_detector/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - REACT_APP_API_HOST=localhost
    depends_on:
      - flask-api

  flask-api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python3 app.py
    ports:
      - "3001:3001"
    depends_on:
      - birdnet-detector

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
